### ISSUE TITLE
[PRE REVIEW]: NiMARE: Neuroimaging Meta-Analysis Research Environment

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews#6]
**Submitting author:** @tsalo (<a href="http://orcid.org/0000-0001-9813-3167">Taylor Salo</a>)
**Repository:** <a href="https://github.com/NBCLab/nimare-paper" target ="_blank">https://github.com/NBCLab/nimare-paper</a>
**Editor:** @pbellec
**Reviewers:** @ltetrel
**Managing EiC:** Pierre Bellec

**Author instructions**

Thanks for submitting your paper to NeuroLibre @tsalo.

@tsalo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://tinyurl.com/y22xx6ux) have already agreed to review for NeuroLibre and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The NeuroLibre submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by roboneuro** [comment]
Hello human, I'm @roboneuro, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@roboneuro commands
```

**Comment by roboneuro** [comment]
PDF failed to compile for issue #6 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.-229bd2334dccb576/0a4ef99965250d4fd89c47d719e28241437c4db5.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA Invalid bit depth (104)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.-229bd2334dccb5
76/0a4ef99965250d4fd89c47d719e28241437c4db5.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.367 ...9965250d4fd89c47d719e28241437c4db5.shtml}

**Comment by roboneuro** [comment]
:point_right::page_facing_up: [View built NeuroLibre Notebook](http://neurolibre-data.conp.cloud/book-artifacts/NBCLab/github.com/nimare-paper/69dcf67bc675d77c04e68a347675e80a6b455b65/_build/html/) :page_facing_up::point_left:

**Comment by pbellec** [comment]
@roboneuro generate nl-notebook

**Comment by roboneuro** [comment]
:point_right::page_facing_up: [View built NeuroLibre Notebook](http://neurolibre-data.conp.cloud/book-artifacts/NBCLab/github.com/nimare-paper/69dcf67bc675d77c04e68a347675e80a6b455b65/_build/html/) :page_facing_up::point_left:

**Comment by pbellec** [comment]
@tsalo did you manage to build the book on our test server? There seemed to be unresolved issues https://github.com/neurolibre/neurolibre-binderhub/issues/33#event-5605990936 and I am getting an error. In the thread I linked, you mentioned 8 hours of computation. This is definitely going to break our quota. We can adjust to a degree, but I would recommend commenting out long computations with a warning that this step takes X hours, and instead downloading pre-generated results.

**Comment by tsalo** [comment]
Per @ltetrel's suggestion, I switched to caching the results. It seemed to be building correctly from the cache. If you want me to switch to building the book from scratch, I could do as you suggest.

**Comment by ltetrel** [comment]
@pbellec for history about this submission, I invite you to read: https://github.com/neurolibre/roboneuro/issues/21
The re-execution did not succeed after 24h (with cache enabled and several retries).
We ended up pushing the build in the repo (few ~MB so that is reasonable), and point jupyter-book cache to this.
https://github.com/NBCLab/nimare-paper/tree/master/content/_build.

As for the issue with data download it is resolved, it was due to osf not working so we ended up using gdrive (history here: https://github.com/neurolibre/neurolibre-binderhub/issues/33)

**Comment by pbellec** [comment]
@ltetrel thanks for pointing that thread, I had somehow missed it.

@tsalo this is great. So two quick comments.

(1) you should think about what brings a lot of value to users vs what is feasible, to decide what to cache and what not to cache. As a rule of thumb: would you attempt to have participants of an educational workshop run that cell? If a computation takes several hours, this is not useful in a reproducible notebook. It's better shared as a script, and cache the results for visualization/further analyses in the notebook. But if it takes, say, 10 mns and is a very meaningful analysis people could experiment with, go ahead. This is something you can address during review. 

(2) currently the book points to mybinder rather than neurolibre test cluster. Please change your `_config.yml` file to point to `binderhub_url             : https://binder.conp.cloud  # The URL of the test Neurolibre BinderHub`
Then I can check the code re-executes correctly on our infrastructure, and move to review.

**Comment by ltetrel** [comment]
@pbellec @tsalo 
For (2) I just fixed an issue where the binder link would not automatically force update to the test cluster (binder.conp.cloud) independently from user repo.
Still there are two links that sticks to mybinder I am not sure why:
http://neurolibre-data.conp.cloud/book-artifacts/NBCLab/github.com/nimare-paper/69dcf67bc675d77c04e68a347675e80a6b455b65/_build/html/resources.html
http://neurolibre-data.conp.cloud/book-artifacts/NBCLab/github.com/nimare-paper/69dcf67bc675d77c04e68a347675e80a6b455b65/_build/html/cbma.html

**Comment by pbellec** [comment]
@roboneuro start review

**Comment by pbellec** [comment]
@roboneuro start review

**Comment by pbellec** [comment]
@tsalo thanks for taking care of the server name in the config file. 
This should fix the issue for this submission - and we'll work on a more systematic solution long term.

At the moment the limit for execution is 1h, but that includes a few operations besides running the notebooks so if you get close to that limit the build may fail. 

FYI our dear @roboneuro seems to be unresponsive, and I have a hard time debugging the logs - I'm very new to this. 
As soon as this is resolved on our end I will initiate review.

**Comment by pbellec** [comment]
@roboneuro assign @pbellec as editor

**Comment by roboneuro** [comment]
OK, the editor is @pbellec

**Comment by pbellec** [comment]
@ltetrel as you already had a close look at this submission, could you add as reviewer?

**Comment by ltetrel** [comment]
@pbellec yes I can, I am still unsure about the state of the production cluster, As for the issues you encountered with roboneuro I don't know what happened we will have to ping agah

**Comment by ltetrel** [comment]
@roboneuro assign @ltetrel as reviewer

**Comment by roboneuro** [comment]
OK, @ltetrel is now a reviewer

**Comment by ltetrel** [comment]
@roboneuro generate nl-notebook

**Comment by roboneuro** [comment]
:point_right::page_facing_up: [View built NeuroLibre Notebook](http://neurolibre-data.conp.cloud/book-artifacts/NBCLab/github.com/nimare-paper/5036aa2185fa62093f30e7bb0161a8c652910acb/_build/html/) :page_facing_up::point_left:

**Comment by ltetrel** [comment]
@roboneuro start review

**Comment by roboneuro** [comment]
OK, I've started the review over in https://github.com/neurolibre/neurolibre-reviews/issues/7.
